<?php
acf_add_local_field_group(array(
	'key' => 'group_5ea95c61c4df2',
	'title' => 'Popup',
	'fields' => array(
		array(
			'key' => 'field_5ea95c6fe88b7',
			'label' => __( 'Enabled', 'otomaties-popup' ),
			'name' => 'popup_enabled',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => __( 'Show popup', 'otomaties-popup' ),
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5ea95c8be88b8',
			'label' => __( 'Show on pages', 'otomaties-popup' ),
			'name' => 'popup_show_on_pages',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => true,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5ea95caee88b9',
			'label' => __( 'Only show once', 'otomaties-popup' ),
			'name' => 'popup_show_once',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => __( 'Show popup only once', 'otomaties-popup' ),
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_a5a16bebb17a2',
			'label' => __( 'Delay', 'otomaties-popup' ),
			'name' => 'popup_delay',
			'type' => 'number',
			'instructions' => __( 'In milliseconds', 'otomaties-popup' ),
			'default_value' => 0,
		),
		array(
			'key' => 'field_5ea95cc9e88ba',
			'label' => __( 'Title', 'otomaties-popup' ),
			'name' => 'popup_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5ea95cdae88bb',
			'label' => __( 'Content', 'otomaties-popup' ),
			'name' => 'popup_content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'otomaties-popup-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'modified' => 1588158110,
));
